name: Hard Reset Data

on:
  # Allow manual triggering
  workflow_dispatch:

jobs:
  complete-refresh:
    runs-on: ubuntu-latest
    environment: supabase
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run complete refresh script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        python hard_reset.py
        
    - name: Cache updated GTFS data
      uses: actions/cache@v4
      with:
        path: cache/gtfs-data-latest.zip
        key: gtfs-data-latest
